package examen2_carlosdiaz;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Diaz
 */
public class examen extends javax.swing.JFrame {

    /**
     * Creates new form examen
     */
    public examen() {
        initComponents();
        modeloBASE = (DefaultTreeModel) tree_chats.getModel();
        ingresar();
        //chat0();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_ingresar = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        tf_user = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_pass = new javax.swing.JPasswordField();
        b_ingresar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jd_crearCuenta = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tf_pwC = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        tf_apellido = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tf_telefono = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        sp_calidadWifi = new javax.swing.JSpinner();
        b_crearCuenta = new javax.swing.JButton();
        tf_userC = new javax.swing.JTextField();
        jd_enviarSolicitud = new javax.swing.JDialog();
        jLabel16 = new javax.swing.JLabel();
        tf_userE = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        b_enviarSoli = new javax.swing.JButton();
        popup_enviarMensaje = new javax.swing.JPopupMenu();
        enviarMensaje = new javax.swing.JMenuItem();
        popup_verMensaje = new javax.swing.JPopupMenu();
        verMensaje = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista_amigos = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tree_chats = new javax.swing.JTree();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        inbox = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        label_hora = new javax.swing.JLabel();
        rb_leido = new javax.swing.JRadioButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        ta_mensaje = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        label_enviadopor = new javax.swing.JLabel();
        barraMensaje = new javax.swing.JProgressBar();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jLabel6.setFont(new java.awt.Font("Candara", 0, 17)); // NOI18N
        jLabel6.setText("Usuario");

        jLabel7.setFont(new java.awt.Font("Candara", 0, 17)); // NOI18N
        jLabel7.setText("Contraseña");

        b_ingresar.setFont(new java.awt.Font("Candara", 0, 17)); // NOI18N
        b_ingresar.setText("Ingresar");
        b_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_ingresarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Candara", 1, 22)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Ingresar cuenta");

        javax.swing.GroupLayout jd_ingresarLayout = new javax.swing.GroupLayout(jd_ingresar.getContentPane());
        jd_ingresar.getContentPane().setLayout(jd_ingresarLayout);
        jd_ingresarLayout.setHorizontalGroup(
            jd_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(jd_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_ingresarLayout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addGroup(jd_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_ingresarLayout.createSequentialGroup()
                            .addGroup(jd_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7))
                            .addGap(43, 43, 43)
                            .addGroup(jd_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tf_pass)
                                .addComponent(tf_user, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jd_ingresarLayout.createSequentialGroup()
                            .addGroup(jd_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jd_ingresarLayout.createSequentialGroup()
                                    .addGap(64, 64, 64)
                                    .addComponent(b_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jd_ingresarLayout.createSequentialGroup()
                                    .addGap(82, 82, 82)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(32, Short.MAX_VALUE)))
        );
        jd_ingresarLayout.setVerticalGroup(
            jd_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 335, Short.MAX_VALUE)
            .addGroup(jd_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_ingresarLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(34, 34, 34)
                    .addGroup(jd_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(tf_user, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jd_ingresarLayout.createSequentialGroup()
                            .addGap(52, 52, 52)
                            .addComponent(jLabel7))
                        .addGroup(jd_ingresarLayout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addComponent(tf_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(49, 49, 49)
                    .addComponent(b_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabel9.setFont(new java.awt.Font("Candara", 1, 22)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Crear cuenta");

        jLabel10.setFont(new java.awt.Font("Candara", 0, 17)); // NOI18N
        jLabel10.setText("User");

        jLabel11.setFont(new java.awt.Font("Candara", 0, 17)); // NOI18N
        jLabel11.setText("Contraseña");

        jLabel12.setFont(new java.awt.Font("Candara", 0, 17)); // NOI18N
        jLabel12.setText("Nombre");

        jLabel13.setFont(new java.awt.Font("Candara", 0, 17)); // NOI18N
        jLabel13.setText("Apellido");

        jLabel14.setFont(new java.awt.Font("Candara", 0, 17)); // NOI18N
        jLabel14.setText("# Teléfono");

        jLabel15.setFont(new java.awt.Font("Candara", 0, 17)); // NOI18N
        jLabel15.setText("Calidad Wi-Fi");

        b_crearCuenta.setText("Crear");
        b_crearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_crearCuentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_crearCuentaLayout = new javax.swing.GroupLayout(jd_crearCuenta.getContentPane());
        jd_crearCuenta.getContentPane().setLayout(jd_crearCuentaLayout);
        jd_crearCuentaLayout.setHorizontalGroup(
            jd_crearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearCuentaLayout.createSequentialGroup()
                .addGroup(jd_crearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crearCuentaLayout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_crearCuentaLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(jd_crearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jd_crearCuentaLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(43, 43, 43)
                                .addComponent(tf_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_crearCuentaLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(43, 43, 43)
                                .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_crearCuentaLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(43, 43, 43)
                                .addComponent(tf_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jd_crearCuentaLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jd_crearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jd_crearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_crearCuentaLayout.createSequentialGroup()
                                .addComponent(tf_userC, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(jLabel15)
                                .addGap(26, 26, 26)
                                .addComponent(sp_calidadWifi, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tf_pwC, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(96, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_crearCuentaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(b_crearCuenta)
                .addGap(41, 41, 41))
        );
        jd_crearCuentaLayout.setVerticalGroup(
            jd_crearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearCuentaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jd_crearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_crearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tf_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_crearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tf_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(jd_crearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel15)
                    .addComponent(sp_calidadWifi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_userC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jd_crearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tf_pwC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(b_crearCuenta)
                .addGap(28, 28, 28))
        );

        jLabel16.setFont(new java.awt.Font("Candara", 0, 17)); // NOI18N
        jLabel16.setText("Usuario");

        jLabel17.setFont(new java.awt.Font("Candara", 1, 22)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Enviar Solicitud");

        b_enviarSoli.setText("Enviar");
        b_enviarSoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_enviarSoliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_enviarSolicitudLayout = new javax.swing.GroupLayout(jd_enviarSolicitud.getContentPane());
        jd_enviarSolicitud.getContentPane().setLayout(jd_enviarSolicitudLayout);
        jd_enviarSolicitudLayout.setHorizontalGroup(
            jd_enviarSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_enviarSolicitudLayout.createSequentialGroup()
                .addGroup(jd_enviarSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(b_enviarSoli)
                    .addGroup(jd_enviarSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jd_enviarSolicitudLayout.createSequentialGroup()
                            .addGap(110, 110, 110)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jd_enviarSolicitudLayout.createSequentialGroup()
                            .addGap(43, 43, 43)
                            .addComponent(jLabel16)
                            .addGap(43, 43, 43)
                            .addComponent(tf_userE, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jd_enviarSolicitudLayout.setVerticalGroup(
            jd_enviarSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_enviarSolicitudLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jd_enviarSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tf_userE, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(b_enviarSoli)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        enviarMensaje.setText("Enviar mensaje");
        enviarMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarMensajeActionPerformed(evt);
            }
        });
        popup_enviarMensaje.add(enviarMensaje);

        verMensaje.setText("Ver Mensajes");
        verMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verMensajeActionPerformed(evt);
            }
        });
        popup_verMensaje.add(verMensaje);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lista_amigos.setFont(new java.awt.Font("Candara", 0, 15)); // NOI18N
        lista_amigos.setModel(new DefaultListModel());
        lista_amigos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lista_amigosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lista_amigos);

        jLabel1.setFont(new java.awt.Font("Candara", 0, 17)); // NOI18N
        jLabel1.setText("Amigos");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Chats");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Privados");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Grupales");
        treeNode1.add(treeNode2);
        tree_chats.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        tree_chats.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tree_chatsMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tree_chats);

        jLabel2.setFont(new java.awt.Font("Candara", 0, 17)); // NOI18N
        jLabel2.setText("Chats");

        inbox.setFont(new java.awt.Font("Candara", 0, 15)); // NOI18N
        inbox.setModel(new DefaultListModel());
        inbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inboxMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(inbox);

        jLabel3.setFont(new java.awt.Font("Candara", 0, 17)); // NOI18N
        jLabel3.setText("Mensajes");

        label_hora.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        label_hora.setText("escrito:");

        rb_leido.setFont(new java.awt.Font("Candara", 0, 15)); // NOI18N
        rb_leido.setText("Leído");

        ta_mensaje.setColumns(20);
        ta_mensaje.setRows(5);
        jScrollPane4.setViewportView(ta_mensaje);

        jButton1.setText("+Amigo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        label_enviadopor.setFont(new java.awt.Font("Candara", 0, 15)); // NOI18N
        label_enviadopor.setText("enviado por:");

        jMenu1.setText("Inicio");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Crear cuenta");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Cerrar Sesión");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(barraMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rb_leido)
                        .addGap(18, 18, 18)
                        .addComponent(label_hora)
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_enviadopor)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                                .addComponent(jScrollPane4)))
                        .addContainerGap(82, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(barraMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(label_enviadopor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_hora)
                    .addComponent(rb_leido))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_ingresarActionPerformed
        // BOTON INGRESAR SESION
        usuarios = new ArrayList();                                             //la reinicio por cualquier cosa
        
        int posicioUuser=0, posicioUuserEnviaSolicitud=0;
        admiUsuarios ac=new admiUsuarios("./Usuarios.ex");
        ac.cargarArchivo();
        for (int i = 0; i < ac.getListaUsuarios().size(); i++) {
            usuarios.add(ac.getListaUsuarios().get(i));
            System.out.println(ac.getListaUsuarios().get(i).getUser());
        }
        
        String userExistente = "" , pwUserExistente;       int contador=0, flag=0;
        for (int i = 0; i < usuarios.size(); i++) {
            userExistente = usuarios.get(i).getUser();    pwUserExistente = usuarios.get(i).getPw();
            if(tf_user.getText().equals(userExistente) && tf_pass.getText().equals(pwUserExistente)){
                usuarioIngresado = usuarios.get(i);
                JOptionPane.showMessageDialog(this, "Bienvenido "+usuarios.get(i).getNombre());
                jd_ingresar.setVisible(false);
                flag=1;     //se ingreso sesion
            }
            contador++;
        }
        //if(contador==(usuarios.size()-1) && flag==0){
        if(flag==1){
            for (int i = 0; i < ac.getListaUsuarios().size(); i++) {
                ///System.out.println( userExistente +i);
                if (userExistente.equals(ac.getListaUsuarios().get(i).getUser())){
                    posicioUuser=i;
                    System.out.println(posicioUuser);
                    break;
                }
            }


            for (int i = 0; i < ac.getListaUsuarios().get(posicioUuser).getSolicitudes().size(); i++) {             //cargo las solicitudes de amistad q le han enviado
                Usuario userEnviaSolicitud = ac.getListaUsuarios().get(posicioUuser).getSolicitudes().get(i);
                int input = JOptionPane.showConfirmDialog(null,
                    "Aceptas la amistad de "+userEnviaSolicitud.getUser(), "Solicitud de amistad",JOptionPane.YES_NO_CANCEL_OPTION);
                // 0=yes, 1=no, 2=cancel
                if(input==0){                                                                                       //la aceptó
                    ac.getListaUsuarios().get(posicioUuser).getSolicitudes().remove(i);                             //la elimino para q no se le repita

                    for (int j = 0; j < ac.getListaUsuarios().size(); j++) {                                        //añadir amigo en el que envio la soli
                        if (userEnviaSolicitud.getUser().equals(ac.getListaUsuarios().get(j).getUser())){
                            posicioUuserEnviaSolicitud=j;
                            userEnviaSolicitud.getAmigos().add(usuarioIngresado);                                   
                        }
                    }

                    ac.getListaUsuarios().get(posicioUuser).getAmigos().add( ac.getListaUsuarios().get(posicioUuserEnviaSolicitud) );       //añadir amigo en el que ingreso sesion
                    
                    admiAmigos aA=new admiAmigos("./Binarios/"+userEnviaSolicitud.getUser()+"A.ex");
                    aA.cargarArchivo();
                    aA.setAmigo(usuarioIngresado);
                    aA.escribirArchivo();
                    
                    admiAmigos aA2=new admiAmigos("./Binarios/"+usuarioIngresado.getUser()+"A.ex");
                    aA2.cargarArchivo();
                    aA2.setAmigo(userEnviaSolicitud);
                    aA2.escribirArchivo();
                }
                System.out.println(input);
            }

            ac.escribirArchivo();
            
            //CARGAR AMIGOS
            admiAmigos aA=new admiAmigos("./Binarios/"+usuarioIngresado.getUser()+"A.ex");
            aA.cargarArchivo();
            DefaultListModel modelo = (DefaultListModel) lista_amigos.getModel();
            for ( Usuario u : aA.getListaAmigos() ) {
                System.out.println(u);
                modelo.addElement(u);
            }
            lista_amigos.setModel(modelo);
            
            tree_chats.setModel(modeloBASE);
        } else{
            JOptionPane.showMessageDialog(this, "Esa cuenta no existe, probá con una diferente");
        }
    }//GEN-LAST:event_b_ingresarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // MOSTRAR VENTANA CREAR CUENTA
        jd_crearCuenta.setModal(true);
        jd_crearCuenta.pack();
        jd_crearCuenta.setLocationRelativeTo(this);
        jd_crearCuenta.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void b_crearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_crearCuentaActionPerformed
        // TODO add your handling code here:
        int wifi = (int) sp_calidadWifi.getValue();
        while(wifi<=0 || wifi>=6){
            wifi = Integer.parseInt( JOptionPane.showInputDialog(this, "La calidad del wifi debe estar entre 1 y 5") );
        }
        Usuario s = new Usuario(tf_userC.getText(), tf_pwC.getText(), wifi, tf_nombre.getText(), tf_apellido.getText(), Integer.parseInt(tf_telefono.getText()));
        
        admiUsuarios ac=new admiUsuarios("./Usuarios.ex");
        ac.cargarArchivo();
        ac.setUsuario(s);
        ac.escribirArchivo();
        
        JOptionPane.showMessageDialog(this, "Se creó la cuenta exitosamente");
        jd_crearCuenta.setVisible(false);
        //usuarios.add(s);
    }//GEN-LAST:event_b_crearCuentaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // MOSTRAR JD DE ENVIAR SOLICITUD
        jd_enviarSolicitud.setModal(true);
        jd_enviarSolicitud.pack();
        jd_enviarSolicitud.setLocationRelativeTo(this);
        jd_enviarSolicitud.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void b_enviarSoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_enviarSoliActionPerformed
        // ENVIAR SOLICITUD
        admiUsuarios ac=new admiUsuarios("./Usuarios.ex");
        ac.cargarArchivo();
        int k=0;
        for (int i = 0; i < ac.getListaUsuarios().size(); i++) {
            
            Usuario menEnviarSoli = ac.getListaUsuarios().get(i);
            if(menEnviarSoli.getUser().equals(tf_userE.getText())){
                menEnviarSoli.getSolicitudes().add(usuarioIngresado);           //para luego cargar estas solicitudes
                ac.escribirArchivo();
                JOptionPane.showMessageDialog(this, "Se envió la solicitud de amistad a "+menEnviarSoli.getNombre());
                System.out.println(ac.getListaUsuarios().get(i).getSolicitudes());
                System.out.println();
                jd_enviarSolicitud.setVisible(false);
            }
            k++;
        }
        if(k!=ac.getListaUsuarios().size()){
            JOptionPane.showMessageDialog(this, "No existe un usuario con ese user. Prueba de nuevo");
        }
    }//GEN-LAST:event_b_enviarSoliActionPerformed

    private void lista_amigosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lista_amigosMouseClicked
        // CLICK DERECHO SOBRE LISTA AMIGOS
        if(evt.isMetaDown()){
            if (lista_amigos.getSelectedIndex() >= 0) {
                popup_enviarMensaje.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_lista_amigosMouseClicked

    private void enviarMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarMensajeActionPerformed
        // LEER MENSAJE A ENVIAR
        System.out.println("");
        DefaultListModel modeloLista = (DefaultListModel) lista_amigos.getModel();
        Usuario usuarioAEnviar = (Usuario) modeloLista.get( lista_amigos.getSelectedIndex() );
        
        //admiPrivados aP = new admiPrivados("./Binarios/"+usuarioIngresado.getUser()+"_"+usuarioAEnviar.getUser()+".ex");
        admiPrivados aP = new admiPrivados("./Binarios/"+"chatsPrivados"+".ex");
        aP.cargarArchivo();
        
        for (int i = 0; i < aP.getListaChatsPrivs().size(); i++) {
        //for (int i = 0; i < 1; i++) {
            cPrivado chat = aP.getListaChatsPrivs().get(i);
            if((chat.getUserAEscribir().getUser().equals(usuarioAEnviar.getUser()) && chat.getUserEscribe().getUser().equals(usuarioIngresado.getUser()))
                    || (chat.getUserAEscribir().getUser().equals(usuarioIngresado.getUser()) && chat.getUserEscribe().getUser().equals(usuarioAEnviar.getUser())) ){
                System.out.println("chat ya creado");
            } else{
                System.out.println("chat nuevo");
                
                String contenido = JOptionPane.showInputDialog(this, "Mensaje:");
                Date h = new Date();
                Mensaje m = new Mensaje(contenido, h, h, false, usuarioIngresado);
                Mensaje m2 = new Mensaje(contenido, h, h, false, usuarioAEnviar);
                
                int tiempo = (int) ((usuarioAEnviar.getWifi()*0.6)+(usuarioIngresado.getWifi()*0.85));
                barraMensaje.setMaximum(tiempo);
                hiloBarra hB = new hiloBarra(barraMensaje, tiempo);
                hB.start();
                
                cPrivado shat = new cPrivado(usuarioAEnviar, usuarioIngresado);
                shat.getMensajes().add(m);
                aP.setChat(shat);
                
                cPrivado shat2 = new cPrivado(usuarioIngresado, usuarioAEnviar);
                shat2.getMensajes().add(m2);
                aP.setChat(shat2);
                
                
                aP.escribirArchivo();
                DefaultTreeModel modeloARBOL = (DefaultTreeModel) tree_chats.getModel();
                DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloARBOL.getRoot();
                
                raiz.getChildAt(0);
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(usuarioAEnviar);
                ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(p);
                System.out.println(" se añade al arbol a "+usuarioAEnviar.getUser());
                break;
            }
        }
        
            //aP.escribirArchivo();
    }//GEN-LAST:event_enviarMensajeActionPerformed

    private void tree_chatsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tree_chatsMouseClicked
        // CLICK DERECHO SOBRE TREE
        if (evt.isMetaDown()) {
            //seleccionar un nodo con click derecho
            int row = tree_chats.getClosestRowForLocation(
                    evt.getX(), evt.getY());
            tree_chats.setSelectionRow(row);
            Object v1
                    = tree_chats.getSelectionPath().
                    getLastPathComponent();
            nodo_seleccionado = (DefaultMutableTreeNode) v1;
            if (nodo_seleccionado.getUserObject() instanceof Usuario) {
                System.out.println("seleccionaste el superior");
                usuario_seleccionado = (Usuario) nodo_seleccionado.getUserObject();
                popup_verMensaje.show(evt.getComponent(),
                        evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_tree_chatsMouseClicked

    private void verMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verMensajeActionPerformed
        // CLICK SOBRE VER MENSAJE CARGA LOS MENSAJES
        reiniciarVistaMensaje();
        admiPrivados aP = new admiPrivados("./Binarios/"+"chatsPrivados"+".ex");
        aP.cargarArchivo();
        
        DefaultListModel modelo = (DefaultListModel) inbox.getModel();
        for (int i = 0; i < aP.getListaChatsPrivs().size(); i++) {
            cPrivado chat = aP.getListaChatsPrivs().get(i);
            
            Usuario usuario_seleccionado = (Usuario) nodo_seleccionado.getUserObject();
                    
            if((chat.getUserAEscribir().getUser().equals(usuario_seleccionado.getUser()) && chat.getUserEscribe().getUser().equals(usuarioIngresado.getUser()))){
                //cargar modelo y enviarlo
                for (int j = 0; j < chat.getMensajes().size(); j++) {
                    Mensaje mtemp = chat.getMensajes().get(j);
                    modelo.addElement(mtemp);
                }
                
            }
        }
        inbox.setModel(modelo);
    }//GEN-LAST:event_verMensajeActionPerformed

    private void inboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inboxMouseClicked
        // CLICK SOBRE MENSAJE
        if (inbox.getSelectedIndex() >= 0) {
            //reiniciarVistaMensaje();
            DefaultListModel modeloLista = (DefaultListModel) inbox.getModel();
            Mensaje msjAnadir = (Mensaje) modeloLista.get( inbox.getSelectedIndex() );
            //label_nombreapellido.setText( correoAnadir.getRemitente().getNombres()+" "+correoAnadir.getRemitente().getAppellidos() );
            label_enviadopor.setText("enviado por "+msjAnadir.getEnviadoPor().getNombre());
            SimpleDateFormat df = new SimpleDateFormat("yyyy/MM/dd h:mm aa");
            label_hora.setText("escrito: "+df.format(msjAnadir.getFechaEnviado()));
            //label_horaC.setText(label_horaC.getText()+" "+df.format(correoAnadir.getFechaEnviado()));
            if(msjAnadir.isLeido()==true){
                rb_leido.setSelected(true);
            } else if(msjAnadir.isLeido()==false){
                rb_leido.setSelected(false);
            }
                
            ta_mensaje.setText(msjAnadir.getContenido());
        } 
    }//GEN-LAST:event_inboxMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(examen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(examen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(examen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(examen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new examen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_crearCuenta;
    private javax.swing.JButton b_enviarSoli;
    private javax.swing.JButton b_ingresar;
    private javax.swing.JProgressBar barraMensaje;
    private javax.swing.JMenuItem enviarMensaje;
    private javax.swing.JList<String> inbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JDialog jd_crearCuenta;
    private javax.swing.JDialog jd_enviarSolicitud;
    private javax.swing.JDialog jd_ingresar;
    private javax.swing.JLabel label_enviadopor;
    private javax.swing.JLabel label_hora;
    private javax.swing.JList<String> lista_amigos;
    private javax.swing.JPopupMenu popup_enviarMensaje;
    private javax.swing.JPopupMenu popup_verMensaje;
    private javax.swing.JRadioButton rb_leido;
    private javax.swing.JSpinner sp_calidadWifi;
    private javax.swing.JTextArea ta_mensaje;
    private javax.swing.JTextField tf_apellido;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JPasswordField tf_pass;
    private javax.swing.JTextField tf_pwC;
    private javax.swing.JTextField tf_telefono;
    private javax.swing.JTextField tf_user;
    private javax.swing.JTextField tf_userC;
    private javax.swing.JTextField tf_userE;
    private javax.swing.JTree tree_chats;
    private javax.swing.JMenuItem verMensaje;
    // End of variables declaration//GEN-END:variables

    ArrayList<Usuario> usuarios = new ArrayList();
    Usuario usuarioIngresado;
    DefaultTreeModel modeloBASE;
    
    DefaultMutableTreeNode nodo_seleccionado;
    Usuario usuario_seleccionado;
    
    public void ingresar() {
        jd_ingresar.setModal(true);
        jd_ingresar.pack();
        jd_ingresar.setLocationRelativeTo(this);
        jd_ingresar.setVisible(true);
        
        //lista_inbox.setModel(new DefaultListModel());       //reiniciar a modelo base de la lisa de inbox
    }
    
    public void chat0(){
        //Usuario s = new Usuario(tf_userC.getText(), tf_pwC.getText(), wifi, tf_nombre.getText(), tf_apellido.getText(), Integer.parseInt(tf_telefono.getText()));
        Usuario temp = new Usuario("temp1", "123", 5, "temporal", "temporal", 0001);
        Usuario temp2 = new Usuario("temp2", "123", 5, "tempora2", "temporal", 0001);
        admiPrivados aP = new admiPrivados("./Binarios/"+"chatsPrivados"+".ex");
        aP.cargarArchivo();
        
        String contenido = JOptionPane.showInputDialog(this, "Mensaje:");
        Date h = new Date();
        Mensaje m = new Mensaje(contenido, h, h, false, temp);

        cPrivado shat = new cPrivado(temp, temp2);
        shat.getMensajes().add(m);

        cPrivado shat2 = new cPrivado(temp2, temp);
        shat2.getMensajes().add(m);
        aP.setChat(shat2);
        aP.escribirArchivo();
    }
    
    public void reiniciarVistaMensaje(){
        inbox.setModel(new DefaultListModel());
        ta_mensaje.setText("");
        label_enviadopor.setText("enviado por: ");
        rb_leido.setSelected(false);
        label_hora.setText("escrito: ");
    }
}
